
// NPM

 console.log("Utikizando CLI - npm")

// NPM INIT

// NPM INIT -Y (FLAG) // INSTALAÇÃO DA PASTA PACKAGE.JSON

//  CRIEI DEPOIS DO EXIT 1" COLOQUEI UMA VIRGULA E CRIEI "SCRIPT"; "NODE .SCRIPT.JS" DEPOIS CANCELADO QUANDO CREI O START

// INSTALANDO A DEPENDÊNCIA JEST (CRIOU UMA PASTA PACKAGE-LOCK-JSON E UMA PASTA DE NODE_MODULES

//  CRIEI DEPOIS script.js" COLOQUEI UMA VIRGULA E CRIEI "SCRIPT"; "NODE .SCRIPT.JS" CRIEI O START: JEST


// E ESTOU UTILIZANDO O COMANDO NPM START