// API INTERFACE DE PROGRAMÇÃO DE APLICAÇÕES

// UMA WEB API É UMA API QUE UTILIZA A INTERNET COMO MEIO DE COMUNICAÇÃO


// SOLICITAÇÕES HTTP , QUE SÃO PROTOCOLOS USADOS PARA TRANSFERIR DADOS.

// API GRATUITAS OTAÇÃO , CLIMA TEMPO , THEMEAL DB, POKE API.


// PROTOCOLOS HTPP (GET, POST, UPDATE E DELETE)


// ESTATO DE SUCESSO 200 OK RESPOSTAS BEM SUCEDIDAS

// 404 NOT FOUND  REPOSTAS DE ERRO DO CLIENTE (400 -499)

// RESPOSTAS DE ERRO DO SERVIOR (500-599)



